### ISSUE TITLE
Error when install

### ISSUE THREAD

**Issue by RomaiinGIT** [Androz2091/discord-backup#13] opened 2019-12-25 18:50 UTC
npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno -4058
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t ssh://git@github.com/discordjs/discord.js.git
npm ERR! enoent
npm ERR! enoent
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Romaiin\AppData\Roaming\npm-cache\_logs\2019-12-25T18_46_43_748Z-debug.log

**Comment by Androz2091** [comment] 2019-12-25 20:09
Duplicate of #4

**Closed by Androz2091** 2019-12-25 20:09 UTC
